# Generated by Django 5.0.6 on 2024-06-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='car_images')),
                ('rent', models.IntegerField()),
                ('city', models.CharField(choices=[('Calicut', 'Calicut'), ('Kochi', 'Kochi'), ('Trivandrum', 'Trivandrum'), ('Kannur', 'Kannur'), ('Bangalore', 'Bangalore'), ('Mangalore', 'Mangalore')], max_length=200)),
                ('isavailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Completed', 'Completed')], default='Order confirmed', max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
