# Generated by Django 5.0.6 on 2024-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Pickup_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Booking confirmed', 'Booking confirmed'), ('Booking Completed', 'Booking Completed')], default='Booking confirmed', max_length=200),
        ),
    ]
