# Generated by Django 5.0.6 on 2024-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_pickup_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Booking confirmed', 'Booking confirmed'), ('Booking completed', 'Booking completed')], default='Booking confirmed', max_length=200),
        ),
    ]
