# Generated by Django 5.0.6 on 2024-07-19 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_order_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Pickup_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
